import type { Metadata } from "next";
import "./globals.css";
import SeperationLayout from "./Components/SeperationLayout/SeperationLayout";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="theme-color" content="#f60000"></meta>
      </Head>
      <body className={`antialiased`}>
        <SeperationLayout>{children}</SeperationLayout>
      </body>
    </html>
  );
}
